apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-05-13T14:33:27Z"
  generation: 3
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1266"
  uid: a171aba9-ffa0-48a5-b49b-d2c78cb76cc2
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-petclinic-rest
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic-rest
    spec:
      containers:
        - image: docker.io/springcommunity/spring-petclinic-rest:3.2.1
          imagePullPolicy: IfNotPresent
          name: spring-petclinic-rest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
    - lastTransitionTime: "2024-05-13T14:33:27Z"
      lastUpdateTime: "2024-05-13T14:42:33Z"
      message: ReplicaSet "spring-petclinic-rest-54f476f68" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-05-13T14:43:35Z"
      lastUpdateTime: "2024-05-13T14:43:35Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 3
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
