apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T14:35:41Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "523"
  uid: 2e95ca1a-dbe1-40aa-94a9-d8abbe420853
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.152.135
  clusterIPs:
  - 10.110.152.135
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30380
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
