apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T14:12:46Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "769"
  uid: 76776349-1ba6-4da3-9a03-8b3f8250dbc6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.242.201
  clusterIPs:
  - 10.96.242.201
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30280
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
